# Generated by Django 5.1.4 on 2024-12-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_name_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
